### ISSUE TITLE
VeinMiner not dropping XP for mined ores.

### ISSUE THREAD

**Issue by NRProjects** [NRProjects/SMP#33]
### Description
XP is not dropped from any blocks mined using the vein miner enchant ability.

### Steps to reproduce
Just veinmine ores that drop xp and watch it not drop xp.

**Comment by paulpugh000** [comment]
Looks to be to a problem with the overloaded [naturallyBreak()](https://jd.papermc.io/paper/1.20/org/bukkit/block/Block.html#breakNaturally(boolean,boolean)) method. It's written in the javadocs, but doesn't seem to be in the API

**Comment by paulpugh000** [comment]
It looks like a Player method of [Player.breakBlock(Block)](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#breakBlock(org.bukkit.block.Block)) could be used to resolve the issue.
