### ISSUE TITLE
Build.gradle forced to build with destination

### ISSUE THREAD

**Issue by paulpugh000** [NRProjects/SMP#34]
Trying to build the jar throws the error of 
`> path may not be null or empty string. path='null'`
The problem originates from line:75 in build.grade

**Comment by NRProjects** [comment]
"This PR adds support for having a local.properties file where you can specify the plugins directory of your local test server. If you set this, when you run jar, the jar will automatically be copied into your plugins folder for easier reloading.

For example, my local properties has this line:
TEST_SERVER_PLUGINS_DIRECTORY=D\:\\Documents\\SMP\\plugins"

**Comment by NRProjects** [comment]
> The default behavior should be building in the `build` folder. If you don't create a local.properties, or don't supply destination for the directory it won't build at all.

Thats fair issue reopened
