### ISSUE TITLE
VeinMiner / TreeCapitator should take hunger equivalent to mining the blocks

### ISSUE THREAD

**Issue by paulpugh000** [NRProjects/SMP#38]
[Mining blocks normally drops your exhaustion by 0.005](https://minecraft.wiki/w/Hunger#Exhaustion_level_increase), but VeinMiner and TreeCapitator don't take any hunger or exhaustion.

**Comment by NRProjects** [comment]
This was thought about but decided against. Its a perk of having the enchantment
