### ISSUE TITLE
[Mods] View offline players inventories

### ISSUE THREAD

**Issue by RealSte4lth** [NRProjects/SMP#44]
Permission to view all player inventories even when offline to check wether a player has spawned in items etc..

**Comment by paulpugh000** [comment]
Theres no way for players to spawn in items, so I don't think this is much of a problem. 

Currently, if there was a scenario where someone stole items from someone else, [CoreProtect](https://github.com/PlayPro/CoreProtect) (which is a 3rd party plugin that gets used on the SMP) restores inventories and rolls back data. [EssentialsX](https://github.com/EssentialsX/Essentials) (the plugin  that handles the `/invsee` command) doesn't have support for checking someone's offline inventory, or ender chest inventory, so its not a simple permission change.
